CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "TblUserTypes" (
    "Id" uuid NOT NULL,
    "Type" text NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TblUserTypes" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240402071116_Initial', '8.0.3');

COMMIT;

START TRANSACTION;

DROP TABLE "TblUserTypes";

CREATE TABLE "TblProdCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" text NOT NULL,
    CONSTRAINT "PK_TblProdCategories" PRIMARY KEY ("Id")
);

CREATE TABLE "UserAccounts" (
    "UserId" uuid NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "IsSeller" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserAccounts" PRIMARY KEY ("UserId")
);

CREATE TABLE "TblProbSubCategory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" integer NOT NULL,
    "ProdSubCategory" text NOT NULL,
    CONSTRAINT "PK_TblProbSubCategory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TblProbSubCategory_TblProdCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "TblProdCategories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TblOrders" (
    "OrderId" uuid NOT NULL,
    "Type" text NOT NULL,
    "UserId" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TblOrders" PRIMARY KEY ("OrderId"),
    CONSTRAINT "FK_TblOrders_UserAccounts_UserId" FOREIGN KEY ("UserId") REFERENCES "UserAccounts" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "TblProducts" (
    "ProductId" uuid NOT NULL,
    "ProductName" text NOT NULL,
    "SellerUserId" uuid NOT NULL,
    "ProbSubCategoryId" integer NOT NULL,
    "Price" double precision NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TblProducts" PRIMARY KEY ("ProductId"),
    CONSTRAINT "FK_TblProducts_TblProbSubCategory_ProbSubCategoryId" FOREIGN KEY ("ProbSubCategoryId") REFERENCES "TblProbSubCategory" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TblProducts_UserAccounts_SellerUserId" FOREIGN KEY ("SellerUserId") REFERENCES "UserAccounts" ("UserId") ON DELETE CASCADE
);

CREATE INDEX "IX_TblOrders_UserId" ON "TblOrders" ("UserId");

CREATE INDEX "IX_TblProbSubCategory_CategoryId" ON "TblProbSubCategory" ("CategoryId");

CREATE INDEX "IX_TblProducts_ProbSubCategoryId" ON "TblProducts" ("ProbSubCategoryId");

CREATE INDEX "IX_TblProducts_SellerUserId" ON "TblProducts" ("SellerUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240411153702_up1', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "TblOrders" DROP CONSTRAINT "FK_TblOrders_UserAccounts_UserId";

ALTER TABLE "TblProducts" DROP CONSTRAINT "FK_TblProducts_UserAccounts_SellerUserId";

ALTER TABLE "UserAccounts" DROP CONSTRAINT "PK_UserAccounts";

ALTER TABLE "UserAccounts" RENAME TO "TblUserAccounts";

ALTER TABLE "TblUserAccounts" ADD CONSTRAINT "PK_TblUserAccounts" PRIMARY KEY ("UserId");

ALTER TABLE "TblOrders" ADD CONSTRAINT "FK_TblOrders_TblUserAccounts_UserId" FOREIGN KEY ("UserId") REFERENCES "TblUserAccounts" ("UserId") ON DELETE CASCADE;

ALTER TABLE "TblProducts" ADD CONSTRAINT "FK_TblProducts_TblUserAccounts_SellerUserId" FOREIGN KEY ("SellerUserId") REFERENCES "TblUserAccounts" ("UserId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240411160859_up3', '8.0.3');

COMMIT;

