// <auto-generated />
using System;
using EasyFarm.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyFarm.Api.Migrations.IdentityDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240415060518_q1")]
    partial class q1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyFarm.Api.Entities.CartList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ProductsProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserAccountsUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductsProductId");

                    b.HasIndex("UserAccountsUserId");

                    b.ToTable("TblCart");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.Orders", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductsProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductsProductId");

                    b.HasIndex("UserId");

                    b.ToTable("TblOrders");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.ProdCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblProdCategories");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.Products", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("OfferPricePrice")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProdCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<Guid?>("SellerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId");

                    b.HasIndex("ProdCategoryId");

                    b.HasIndex("SellerUserId");

                    b.ToTable("TblProducts");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.UserAccounts", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("TblUserAccounts");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.CartList", b =>
                {
                    b.HasOne("EasyFarm.Api.Entities.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProductId");

                    b.HasOne("EasyFarm.Api.Entities.UserAccounts", "UserAccounts")
                        .WithMany()
                        .HasForeignKey("UserAccountsUserId");

                    b.Navigation("Products");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.Orders", b =>
                {
                    b.HasOne("EasyFarm.Api.Entities.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProductId");

                    b.HasOne("EasyFarm.Api.Entities.UserAccounts", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Products");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EasyFarm.Api.Entities.Products", b =>
                {
                    b.HasOne("EasyFarm.Api.Entities.ProdCategory", "ProdCategory")
                        .WithMany()
                        .HasForeignKey("ProdCategoryId");

                    b.HasOne("EasyFarm.Api.Entities.UserAccounts", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerUserId");

                    b.Navigation("ProdCategory");

                    b.Navigation("Seller");
                });
#pragma warning restore 612, 618
        }
    }
}
